services:
  mysql:
    image: mysql:8.0
    container_name: zenml_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zenml
      MYSQL_USER: zenml
      MYSQL_PASSWORD: zenml
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - geo

  zenml-server:
    image: zenmldocker/zenml-server
    ports:
      - "8080:8080"
    # environment:
    #   - ZENML_STORE_URL=mysql://root:password@host.docker.internal/zenml
    links:
      - mysql
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    networks:
      - geo

  # MongoDB for your application data
  mongo:
    image: mongo:latest
    container_name: "geo_engineering_mongo"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "geo_engineering"
      MONGO_INITDB_ROOT_PASSWORD: "geo_engineering"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - geo

  ngrok:
    image: ngrok/ngrok:latest
    container_name: zenml_ngrok
    depends_on:
      - zenml-server
    env_file:
      - .env
    command: http zenml-server:8080
    ports:
      - "4040:4040"
    networks:
      - geo

  # Qdrant Vector Database
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   container_name: qdrant
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - ./data/qdrant_data:/qdrant/storage
  #   restart: unless-stopped
  #   networks:
  #     - geo

volumes:
  mysql_data:
  mongo_data:

networks:
  geo:
    driver: bridge